# server port
server:
  port: 8082

# database
spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:~/IdeaProjects/CloudMonologue/db_dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ON_SECRET
            scope: profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/{registrationId}'
          google:
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/{registrationId}'
            client-name: Google
            scope: profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# etc.
logging:
  level:
    com.ll.EduBridge: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: www.cloudm.ysj.today
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: cm
  jwt:
    secretKey: ON_SECRET
  accessToken:
    expirationSec: '#{60*60}'
  temp:
    dirPath: c:/temp/cm_dev/temp
  genFile:
    dirPath: c:/temp/cm_dev

#openai:
#  model: gpt-4-turbo-preview # 미정
#  secret-key: ON_SECRET
#  api:
#    key: ON_SECRET
#    url: https://api.openai.com/v1/chat/completions